# Generated by Django 3.2.7 on 2021-10-01 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity_ingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_ingredient', to='foodgram.ingredients'),
        ),
        migrations.AlterField(
            model_name='quantity_ingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_recipe', to='foodgram.recipe'),
        ),
    ]
