# Generated by Django 3.0.5 on 2021-09-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_auto_20210919_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredientos', through='foodgram.Quantity_ingredients', to='foodgram.Ingredients', verbose_name='Ингридиенты'),
        ),
    ]
