# Generated by Django 3.2.7 on 2021-10-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shopping_cart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='add_shopping_cart'),
        ),
    ]
